export default {
  events: {
    CREATE_LOCATION: 'CREATE_LOCATION',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    DELETE_LOCATION: 'DELETE_LOCATION',
    LOG_ACTIVITY: 'LOG_ACTIVITY',
    CLEAR_SALES_CACHE: 'CLEAR_SALES_CACHE',
    COUNT_DAILY_SALES: 'COUNT_DAILY_SALES',
    CLEAR_PRODUCT_CACHE: 'CLEAR_PRODUCT_CACHE',
    CREATE_END_OF_DAY: 'CREATE_END_OF_DAY',
    CLEAR_INVENTORY_CACHE: 'CLEAR_INVENTORY_CACHE',
    CREATE_ORDER_RECORD: 'CREATE_ORDER_RECORD',
    SEND_PASSWORD_TO_EMAIL: 'SEND_PASSWORD_TO_EMAIL',
    CREATE_ITEM_QUICKBOOKS: 'CREATE_ITEM_QUICKBOOKS',
    CREATE_REQUISITION_QUICKBOOKS: 'CREATE_REQUISITION_QUICKBOOKS'
  }
};
